models:
  xgboost_classifier:
    class: XGBClassifier
    parameters:
      learning_rate: [0.01, 0.05, 0.1]
      max_depth: [3, 5, 7]
      n_estimators: [50, 100, 200]
      gamma: [0,  0.1, 5]

  gradient_boosting_classifier:
    class: GradientBoostingClassifier
    parameters:
      n_estimators: [50, 100, 200]
      criterion: ["friedman_mse", "squared_error"]
      max_depth: [3, 5]

  support_vector_classifier:
    class: SVC
    parameters:
      kernel: ["linear", "rbf", "poly"]
      gamma: ["scale", "auto"]

  random_forest_classifier:
    class: RandomForestClassifier
    parameters:
      max_depth: [-none, 5, 10]
      min_samples_split: [ 2, 5, 10]
      min_samples_leaf: [1, 2, 4]

